import type { HomeContent } from "@/lib/home/types";

export const fallbackHomeContent: HomeContent = {
    hero: {
        title: "Chinh phục học bổng Trung Quốc cùng Mentor ChinaHack",
        subtitle: "Lộ trình cá nhân hóa, từ hồ sơ đến phỏng vấn.",
        ctaText: "Nhận tư vấn miễn phí",
        ctaHref: "#lead-form",
        mentorImage: {
            src: "/images/mentor-hero.webp",
            alt: "Mentor ChinaHack",
            width: 640,
            height: 860,
        },
    },
    about: {
        heading: "Về chúng tôi",
        body: "ChinaHack hỗ trợ học viên tối ưu hồ sơ và chiến lược học bổng.",
        highlightQuote: "Đúng lộ trình đúng, cơ hội học bổng mở rộng hơn.",
        image: {
            src: "/logo.svg",
            alt: "ChinaHack visual",
        },
    },
    whyChoose: [
        {
            id: "w1",
            title: { en: "Hands-on Mentors", vi: "Mentor thực chiến", zh: "实战导师" },
            description: { en: "Experience from real profiles", vi: "Kinh nghiệm từ hồ sơ thật", zh: "来自真实档案的经验" },
            icon: "book",
        },
        {
            id: "w2",
            title: { en: "Clear Roadmap", vi: "Lộ trình rõ ràng", zh: "清晰的路线图" },
            description: { en: "Stays on schedule", vi: "Bám sát mốc thời gian", zh: "紧跟时间节点" },
            icon: "target",
        },
        {
            id: "w3",
            title: { en: "Quality Resources", vi: "Tài nguyên chất lượng", zh: "优质资源" },
            description: { en: "Templates and checklists", vi: "Mẫu bài và checklist", zh: "模板和清单" },
            icon: "medal",
        },
        {
            id: "w4",
            title: { en: "Supportive Community", vi: "Cộng đồng hỗ trợ", zh: "支持性社区" },
            description: { en: "Ongoing companionship", vi: "Đồng hành xuyên suốt", zh: "全程陪伴" },
            icon: "network",
        },
    ],
    mentors: [
        {
            id: "m1",
            name: { en: "Li Jiapeng", vi: "Li Jiapeng", zh: "李嘉鹏" },
            role: { en: "Academic Advisor", vi: "Cố vấn học thuật", zh: "学术顾问" },
            avatar: "/images/mentor-a.webp",
            headline: { en: "AI, Robotics and Research Direction in China", vi: "AI, Robotics và định hướng nghiên cứu tại Trung Quốc", zh: "人工智能、机器人和中国研究方向" },
            shortBio: { en: "Supporting mentees in engineering, AI and research scholarships.", vi: "Đồng hành cùng mentee ở nhóm ngành kỹ thuật, AI và học bổng nghiên cứu.", zh: "支持工程、AI和研究奖学金领域的学生。" },
            fullBio: { en: "In-depth support from academic guidance, building research profiles to scholarship application strategy for engineering students in China.", vi: "Hỗ trợ chuyên sâu từ định hướng học thuật, xây hồ sơ nghiên cứu đến chiến lược xin học bổng cho các bạn theo đuổi nhóm ngành kỹ thuật tại Trung Quốc.", zh: "为在中国攻读工程专业的学生提供从学术指导、建立研究档案到奖学金申请策略的深入支持。" },
            focusAreas: [
                { en: "Academic Guidance", vi: "Định hướng học thuật", zh: "学术指导" },
                { en: "Research Profile", vi: "Hồ sơ nghiên cứu", zh: "研究档案" },
                { en: "Engineering Scholarship", vi: "Học bổng kỹ thuật", zh: "工程奖学金" },
            ],
            achievements: [
                { en: "Pursued AI and Computer Vision research in international environment.", vi: "Theo đuổi hướng nghiên cứu AI và Computer Vision trong môi trường quốc tế.", zh: "在国际环境中从事AI和计算机视觉研究。" },
                { en: "Experience with Robotics, computer vision models and intelligent systems.", vi: "Có kinh nghiệm với Robotics, mô hình thị giác máy tính và hệ thống thông minh.", zh: "具有机器人、计算机视觉模型和智能系统的经验。" },
                { en: "Led academic projects with research-oriented applications.", vi: "Từng tham gia và dẫn dắt các dự án học thuật theo định hướng ứng dụng.", zh: "主导过面向应用的学术项目。" },
                { en: "Perfect for profiles needing academic depth and research thinking.", vi: "Phù hợp mentoring cho các hồ sơ cần chiều sâu học thuật và tư duy nghiên cứu.", zh: "适合需要学术深度和研究思维的档案。" },
            ],
            quote: { en: "A strong profile doesn't just need scores, but a clear academic direction and research potential.", vi: "Một hồ sơ mạnh không chỉ cần điểm số, mà cần kể rõ định hướng học thuật và tiềm năng nghiên cứu của bạn.", zh: "一份强有力的档案不仅需要成绩，还需要清晰的学术方向和研究潜力。" },
        },
        {
            id: "m2",
            name: { en: "Le Thi Phuong Anh", vi: "Lê Thị Phương Anh", zh: "黎氏芳英" },
            role: { en: "ChinaHack - Marketing Manager", vi: "ChinaHack - Marketing Manager", zh: "ChinaHack - 市场经理" },
            avatar: "/images/mentor-b.webp",
            headline: { en: "Academic Model through Extracurriculars and Scholarships", vi: "Hình mẫu học thuật qua hoạt động ngoại khóa và học bổng", zh: "通过课外活动和奖学金的学术模式" },
            shortBio: { en: "Profile positioning balance between academics and personal activities.", vi: "Phụ trách định vị hồ sơ nổi bật, cân bằng giữa học thuật và hoạt động cá nhân.", zh: "档案定位突出，平衡学术和个人活动。" },
            fullBio: { en: "Focus on building clear profile story, consistent and help mentees showcase personal identity, academic ability and depth of activities.", vi: "Tập trung xây dựng câu chuyện hồ sơ rõ ràng, nhất quán, giúp mentee thể hiện được bản sắc cá nhân, năng lực học thuật và chiều sâu hoạt động ngoại khóa.", zh: "专注于建立清晰一致的档案故事，帮助学生展示个人身份、学术能力和活动深度。" },
            focusAreas: [
                { en: "Build Personal Story", vi: "Xây dựng personal story", zh: "建立个人故事" },
                { en: "Extracurricular Activities", vi: "Hoạt động ngoại khóa", zh: "课外活动" },
                { en: "Scholarship Positioning", vi: "Scholarship positioning", zh: "奖学金定位" },
            ],
            achievements: [
                { en: "IELTS 8.0 and strong academic foundation for international profiles.", vi: "IELTS 8.0 và nền tảng học thuật mạnh cho hồ sơ quốc tế.", zh: "雅思8.0和国际档案的强大学术基础。" },
                { en: "Experience highlighting profiles through personal communication and community activities.", vi: "Kinh nghiệm làm nổi bật hồ sơ qua truyền thông cá nhân và hoạt động cộng đồng.", zh: "通过个人沟通和社区活动突出档案的经验。" },
                { en: "Help mentees tell compelling and in-depth profile stories.", vi: "Đồng hành cùng mentee trong cách kể câu chuyện hồ sơ thuyết phục và có chiều sâu.", zh: "帮助学生讲述有说服力和深度的档案故事。" },
                { en: "Perfect for profiles needing higher visibility beyond pure scores.", vi: "Phù hợp với các hồ sơ cần tăng độ nổi bật ngoài điểm số thuần túy.", zh: "适合需要超越纯分数获得更高知名度的档案。" },
            ],
            quote: { en: "Real strength doesn't lie in having many achievements, but in connecting them into a purposeful story.", vi: "Điểm mạnh thật sự của hồ sơ không nằm ở việc có thật nhiều thành tích, mà ở cách bạn kết nối chúng thành một câu chuyện có định hướng.", zh: "真正的优势不在于拥有许多成就，而在于将它们连接成一个有目的的故事。" },
        },
        {
            id: "m3",
            name: { en: "ChinaHack Mentor Team", vi: "ChinaHack Mentor Team", zh: "ChinaHack导师团队" },
            role: { en: "Mentorship & Scholarship Application", vi: "Mentorship & Scholarship Application", zh: "指导和奖学金申请" },
            avatar: "/images/mentor-c.webp",
            headline: { en: "Academic Guidance, Profile Building and Scholarship Application", vi: "Định hướng học thuật, xây dựng hồ sơ và nộp học bổng", zh: "学术指导、档案建设和奖学金申请" },
            shortBio: { en: "Mentor team accompanying from initial guidance to final interview.", vi: "Mentor team đồng hành xuyên suốt từ định hướng ban đầu đến vòng phỏng vấn cuối.", zh: "导师团队从初始指导到最终面试全程陪伴。" },
            fullBio: { en: "Coordinated mentoring at each stage: major selection, university choice, scholarship optimization, profile writing and interview preparation for clear and proactive journey.", vi: "Đội ngũ mentor phối hợp theo từng giai đoạn: định hướng ngành học, chọn trường, tối ưu học bổng, viết hồ sơ và luyện phỏng vấn để mentee có một hành trình rõ ràng và chủ động.", zh: "协调的指导覆盖每个阶段：专业选择、大学选择、奖学金优化、档案编写和面试准备，为学生提供明确和主动的旅程。" },
            focusAreas: [
                { en: "Choose Right University", vi: "Chọn trường phù hợp", zh: "选择合适的大学" },
                { en: "Optimize Scholarship", vi: "Tối ưu học bổng", zh: "优化奖学金" },
                { en: "Interview Preparation", vi: "Luyện phỏng vấn", zh: "面试准备" },
            ],
            achievements: [
                { en: "Mentoring through each stage, not just isolated profile editing.", vi: "Mentoring theo mô hình đồng hành từng giai đoạn, không chỉ sửa hồ sơ đơn lẻ.", zh: "通过每个阶段的指导，而不仅仅是孤立的档案编辑。" },
                { en: "Focus on fit between ability, goals and scholarship strategy.", vi: "Tập trung vào sự phù hợp giữa năng lực, mục tiêu và chiến lược học bổng.", zh: "专注于能力、目标和奖学金策略之间的契合度。" },
                { en: "Priority on quick feedback, clear checklists and personalized roadmaps for each mentee.", vi: "Ưu tiên phản hồi nhanh, checklist rõ ràng và lộ trình cá nhân hóa cho từng mentee.", zh: "优先提供快速反馈、清晰的检查清单和个性化的学生路线图。" },
                { en: "Perfect for students needing a close companion from start to end.", vi: "Phù hợp với học sinh cần một người đồng hành sát sao từ đầu đến cuối.", zh: "适合需要从头到尾密切陪伴的学生。" },
            ],
            quote: { en: "ChinaHack's goal isn't just to help you submit, but to help you understand why it can reach scholarship.", vi: "Mục tiêu của ChinaHack không phải chỉ giúp bạn nộp hồ sơ, mà là giúp bạn hiểu vì sao hồ sơ đó có thể chạm tới học bổng.", zh: "ChinaHack的目标不仅仅是帮助您提交，而是帮助您理解为什么它能获得奖学金。" },
        },
    ],
    stats: [
        { id: "s1", label: { en: "Students", vi: "Học viên", zh: "学生" }, value: 120, suffix: "+" },
        { id: "s2", label: { en: "Scholarship Rate", vi: "Học bổng", zh: "奖学金率" }, value: 85, suffix: "%" },
        { id: "s3", label: { en: "Partners", vi: "Đối tác", zh: "合作伙伴" }, value: 30, suffix: "+" },
        { id: "s4", label: { en: "Years of Experience", vi: "Năm kinh nghiệm", zh: "年经验" }, value: 6, suffix: "+" },
    ],
    process: [
        {
            id: "p1",
            title: { en: "Intake", vi: "Nhận hồ sơ", zh: "接收资料" },
            description: { en: "Collect input information and goals.", vi: "Thu thập thông tin đầu vào và mục tiêu.", zh: "收集输入信息和目标。" },
        },
        {
            id: "p2",
            title: { en: "Assessment", vi: "Đánh giá", zh: "评估" },
            description: { en: "Analyze profile, GPA and scholarship level.", vi: "Phân tích profile, GPA và mức học bổng.", zh: "分析档案、GPA和奖学金水平。" },
        },
        {
            id: "p3",
            title: { en: "Roadmap Planning", vi: "Lập lộ trình", zh: "制定路线图" },
            description: { en: "Build deadlines and assign categories.", vi: "Xây dựng các mốc hạn và phân công hạng mục.", zh: "建立截止日期并分配类别。" },
        },
        {
            id: "p4",
            title: { en: "Profile Completion", vi: "Hoàn thiện hồ sơ", zh: "完善档案" },
            description: { en: "Essay, CV, recommendation and feedback.", vi: "Essay, CV, recommendation và phản hồi.", zh: "文书、简历、推荐信和反馈。" },
        },
        {
            id: "p5",
            title: { en: "Submission", vi: "Nộp đơn", zh: "提交申请" },
            description: { en: "Track submission deadlines and follow up on results.", vi: "Canh mốc submit và theo dõi kết quả.", zh: "把握提交时间并跟踪结果。" },
        },
        {
            id: "p6",
            title: { en: "Interview", vi: "Phỏng vấn", zh: "面试" },
            description: { en: "Practice and support before the interview.", vi: "Luyện tập và support trước buổi interview.", zh: "面试前的练习和支持。" },
        },
    ],
    services: [
        {
            id: "sv1",
            name: "Basic",
            description: { en: "Basic profile assessment.", vi: "Đánh giá hồ sơ cơ bản.", zh: "基础档案评估。" },
            audience: {
                en: "Suitable for students needing initial direction and wanting to know where to start.",
                vi: "Phù hợp với học sinh cần định hướng ban đầu và muốn biết nên bắt đầu từ đâu.",
                zh: "适合需要初步方向、想知道从何入手的学生。",
            },
            supportLabel: { en: "Starter guidance", vi: "Starter guidance", zh: "入门指导" },
            supportNote: {
                en: "Focused on helping you see your profile foundation, shortlist scholarships and the next step.",
                vi: "Tập trung giúp bạn nhìn rõ nền hồ sơ, shortlist học bổng và bước kế tiếp.",
                zh: "专注于帮助您了解档案基础、筛选奖学金和下一步。",
            },
            features: [
                { en: "Profile analysis", vi: "Phân tích profile", zh: "档案分析" },
                { en: "Scholarship suggestions", vi: "Gợi ý học bổng", zh: "奖学金建议" },
                { en: "1 consultation session", vi: "1 buổi tư vấn", zh: "1次咨询" },
            ],
            ctaText: { en: "Choose Basic", vi: "Chọn Basic", zh: "选择 Basic" },
            ctaHref: "#lead-form",
        },
        {
            id: "sv2",
            name: "Standard",
            description: { en: "Profile revision roadmap.", vi: "Lộ trình chỉnh sửa hồ sơ.", zh: "档案修改路线图。" },
            audience: {
                en: "Suitable for most candidates who already have a goal and need a clear roadmap to optimize their profile.",
                vi: "Phù hợp với đa số ứng viên đã có mục tiêu và cần một roadmap rõ ràng để tối ưu hồ sơ.",
                zh: "适合大多数已有目标、需要清晰路线图来优化档案的申请者。",
            },
            supportLabel: { en: "Roadmap + coaching", vi: "Roadmap + coaching", zh: "路线图 + 辅导" },
            supportNote: {
                en: "Balances profile strategy, milestone coaching and self-directed execution.",
                vi: "Cân bằng giữa chiến lược hồ sơ, coaching theo từng mốc và khả năng tự triển khai.",
                zh: "平衡档案策略、阶段性辅导和自主执行能力。",
            },
            features: [
                { en: "Essay review", vi: "Essay review", zh: "文书审阅" },
                { en: "Application checklist", vi: "Checklist nộp đơn", zh: "申请清单" },
                { en: "2 coaching sessions", vi: "2 buổi coaching", zh: "2次辅导" },
            ],
            ctaText: { en: "Choose Standard", vi: "Chọn Standard", zh: "选择 Standard" },
            ctaHref: "#lead-form",
            highlightLabel: { en: "Most Popular", vi: "Phổ biến nhất", zh: "最受欢迎" },
            isFeatured: true,
        },
        {
            id: "sv3",
            name: "Premium",
            description: { en: "Companionship until results.", vi: "Đồng hành đến khi có kết quả.", zh: "陪伴至出结果。" },
            audience: {
                en: "Suitable for students wanting closer support at key milestones and personalized help.",
                vi: "Phù hợp với học sinh muốn được theo sát hơn ở các mốc quan trọng và cần hỗ trợ cá nhân hóa.",
                zh: "适合希望在关键节点得到更密切支持及个性化帮助的学生。",
            },
            supportLabel: { en: "High-touch mentorship", vi: "High-touch mentorship", zh: "深度指导" },
            supportNote: {
                en: "Mentor accompanies you deeper in major decisions, profile feedback and interview preparation.",
                vi: "Mentor đồng hành sâu hơn trong các quyết định lớn, phản hồi hồ sơ và chuẩn bị phỏng vấn.",
                zh: "导师在重大决策、档案反馈和面试准备上给予更深入的陪伴。",
            },
            features: [
                { en: "1-1 mentor", vi: "1-1 mentor", zh: "1对1导师" },
                { en: "Mock interview", vi: "Phỏng vấn thử", zh: "模拟面试" },
                { en: "Post-submission follow-up", vi: "Theo dõi sau nộp", zh: "提交后跟踪" },
            ],
            ctaText: { en: "Choose Premium", vi: "Chọn Premium", zh: "选择 Premium" },
            ctaHref: "#lead-form",
            premiumNote: {
                en: "Extra room to handle feedback rounds, last-minute edits near deadlines and unexpected situations.",
                vi: "Có thêm không gian để xử lý các vòng phản hồi, chỉnh sửa sát deadline và chuẩn bị các tình huống phát sinh.",
                zh: "有更多空间处理反馈轮次、临近截止日期的修改以及应对突发情况。",
            },
        },
    ],
    universities: [
        { id: "u1", name: "Tsinghua", logo: "/images/university-1.webp" },
        {
            id: "u2",
            name: "Peking University",
            logo: "/images/university-2.webp",
        },
        { id: "u3", name: "Fudan", logo: "/images/university-3.webp" },
        { id: "u4", name: "SJTU", logo: "/images/university-4.webp" },
    ],
    successStories: [
        {
            id: "ss1",
            studentName: "Minh Anh",
            avatar: "/images/student-1.webp",
            quote: {
                en: "Profile was clearly optimized and easier to understand.",
                vi: "Hồ sơ được tối ưu rõ rệt và dễ hiểu hơn.",
                zh: "档案得到了明显优化，更易理解。",
            },
            outcome: {
                en: "Received 80% scholarship",
                vi: "Nhận học bổng 80%",
                zh: "获得80%奖学金",
            },
        },
        {
            id: "ss2",
            studentName: "Quang Huy",
            avatar: "/images/student-2.webp",
            quote: {
                en: "Interview preparation greatly reduced anxiety.",
                vi: "Phỏng vấn giảm cảm giác lo lắng rất nhiều.",
                zh: "面试准备大大减轻了焦虑。",
            },
            outcome: {
                en: "Admitted to master's program",
                vi: "Trúng tuyển chương trình thạc sĩ",
                zh: "被录取参加硕士项目",
            },
        },
    ],
    blogTabs: [
        { id: "all", label: { en: "All", vi: "Tất cả", zh: "全部" }, slug: "all" },
        { id: "scholarship", label: { en: "Scholarship", vi: "Học bổng", zh: "奖学金" }, slug: "hoc-bong" },
        { id: "guide", label: { en: "Guide", vi: "Hướng dẫn", zh: "指南" }, slug: "huong-dan" },
    ],
    community: [
        {
            id: "c1",
            name: "Facebook",
            description: "Cập nhật sàn học bổng và chia sẻ kinh nghiệm.",
            href: "https://facebook.com",
            bannerImage: "/images/community-facebook.webp",
        },
        {
            id: "c2",
            name: "TikTok",
            description: "Video ngắn về quy trình và tips nhanh.",
            href: "https://tiktok.com",
            bannerImage: "/images/community-tiktok.webp",
        },
        {
            id: "c3",
            name: "YouTube",
            description: "Hướng dẫn chi tiết và webinar.",
            href: "https://youtube.com",
            bannerImage: "/images/community-youtube.webp",
        },
    ],
    leadForm: {
        title: "Đăng ký đánh giá hồ sơ",
        subtitle: "Nhận lộ trình cá nhân hóa trong 24h",
        submitText: "Nhận đánh giá hồ sơ miễn phí",
        loadingText: "Đang xử lý...",
    },
};
